name: CI
on:
  pull_request:
  push:
jobs:
  compile_and_unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"
      - name: Build and Test
        run: sbt -v -Dfile.encoding=UTF-8 +test